version: '3'
services:
  django:
    build: ../../
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "./wait-for-it.sh db:5432&&
             python manage.py migrate &&
             python manage.py benchmark_db"
    volumes:
      - ./../../:/app
  db:
    image: postgres:14.0-alpine
    env_file:
      - .env